### ISSUE TITLE
License and terms of modification

### ISSUE THREAD

**Issue by aggregate1166877** [CrankerMan/TME-Shaders#3]
Hi there, I see your code says that before anything can be modified, I first need to read the terms of modification.

I have checked the zip I downloaded as well as the repo readme, I have not seen any license or modification / distribution information. What license is this under?

Kind regards

**Comment by CrankerMan** [comment]
If it says anything like that in the code then it's probably because the pack was based on Chocapic13's old shaderpacks. So you'd have to find out what he says about modifications. Last I know they're ok as long as credit in the packs name is given and no money is made via the downloads, but don't count on this being true anymore.

**Comment by aggregate1166877** [comment]
Thanks for the info @CrankerMan :)

**Comment by aggregate1166877** [comment]
I couldn't find an original Chocapi13 license,  but according the [espen96 Loop](https://github.com/espen96/Loop) project, the original Chocapi13 license is as follows:

<hr>

### Sharing a modified version of my shaders:
* You are not allowed to claim any of the code included in "Chocapic13' shaders" as your own
* You can share a modified version of my shaders if you respect the following title scheme : " -Name of the shaderpack- (Chocapic13' Shaders edit) "
* You cannot use any monetizing links (for example adfoc.us ; adf.ly)
* The rules of modification and sharing have to be same as the one here (copy paste all these rules in your post and change depending if you allow modification or not), you cannot make your own rules, you can only choose if you allow redistribution.
* I have to be clearly credited
* You cannot use any version older than "Chocapic13' Shaders V4" as a base, however you can modify older versions for personal use

Common sense : if you want a feature from another shaderpack or want to use a piece of code found on the web, make sure the code is open source. In doubt ask the creator.

Common sense #2 : share your modification only if you think it adds something really useful to the shaderpack(not only 2-3 constants changed)

### Special level of permission; with written permission from Chocapic13, on request if you think your shaderpack is an huge modification from the original:
* Allows to use monetizing links
* Allows to create your own sharing rules
* Shaderpack name can be chosen
* Listed on Chocapic13' shaders official thread
* Chocapic13 still have to be clearly credited

### Using this shaderpack in a video or a picture:
* You are allowed to use this shaderpack for screenshots and videos if you give the shaderpack name in the description/message
* You are allowed to use this shaderpack in monetized videos if you respect the rule above.

### Minecraft websites:
* The download link must redirect to the download link given in the shaderpack's official thread
* There has to be a link to the shaderpack's official thread
* You are not allowed to add any monetizing link to the shaderpack download

If you are not sure about what you are allowed to do or not, PM Chocapic13 on http://www.minecraftforum.net/.

**Not respecting these rules can and will result in a request of thread/download shutdown to the host/administrator, with or without warning. Intellectual property stealing is punished by law.**

<hr>

I think the above is sufficient, we can close this ticket.
